### ISSUE TITLE
How to get 2d lane line detection metrics？

### ISSUE THREAD

**Issue by Hzy98** [OpenPerceptionX/PersFormer_3DLane#35]
The evaluation results  include F-measure, Recall, x error, etc.  Are these the results of 3d task? So how should I get the metrics for the 2d task?

**Comment by ilnehc** [comment]
@Hzy98 Yes. Both 2D/3D results are saved in the JSON file:
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/584cf52ae07ea1288fc67f75cf1f0e2688885769/experiments/runner.py#L769-L780
You can use the eval script in OpenLane (refer to https://github.com/OpenPerceptionX/OpenLane/blob/main/eval/LANE_evaluation/README.md) to get the final metrics.
Since you are interested in 2D evaluation, please pay attention to https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/30 as well.

**Comment by Hzy98** [comment]
got it. thanks for the reply.
