### ISSUE TITLE
能用到其他数据集吗

### ISSUE THREAD

**Issue by Kailthen** [OpenPerceptionX/PersFormer_3DLane#7]
你好，比如想用nuscenes测试一下模型效果，推理时unit_update_projection_extrinsic函数的参数extrinsics，该怎么设定呢？
除了org_w,org_h,cam_height,pitch等参数，还有其他的参数吗

感谢~

**Comment by Kailthen** [comment]
@dyfcalid 感谢解答。
我试着测试了，用你们的数据集正常；用nuscene时发现生成的vis_ipm图像不对，怀疑是json里extrinsic参数有问题。那么extrinsic这个参数，是指camera to ego的Transformation Matrix吗，或者是world to camera?

**Comment by dyfcalid** [comment]
> @dyfcalid 感谢解答。 我试着测试了，用你们的数据集正常；用nuscene时发现生成的vis_ipm图像不对，怀疑是json里extrinsic参数有问题。那么extrinsic这个参数，是指camera to ego的Transformation Matrix吗，或者是world to camera?

是的，camera to ego，相机坐标系到车辆坐标系

**Comment by laqangela** [comment]
请问可以向您要一份

> @dyfcalid 感谢解答。 我试着测试了，用你们的数据集正常；用nuscene时发现生成的vis_ipm图像不对，怀疑是json里extrinsic参数有问题。那么extrinsic这个参数，是指camera to ego的Transformation Matrix吗，或者是world to camera?

请问可以向您要一份用persformer算法test nuscenes数据集的代码吗？我有些急用，来不及自己研究了

**Comment by jasmine-97** [comment]
你好，直接使用carema to ego测试结果是正确的吗？因为我尝试了一下ipm的可视化结果有问题，是因为openlane标注的waymo数据集的x，y和z轴和正常的偏向不同导致吗？

**Comment by RicardLee** [comment]
Hi, could you provide related  visualization and code ?

________________________________

**Comment by jasmine-97** [comment]
I used the original code of the Persformer model to predict front-view images in the NuScenes dataset, and I used the corresponding intrinsic and extrinsic parameters. However, when using Persformer for inference, the generated JSON results in result_3d show empty lane_lines. Besides changing the intrinsic and extrinsic parameters in the ground truth file, are there any other parameters that need to be adjusted during testing?
![图片](https://github.com/OpenDriveLab/PersFormer_3DLane/assets/87070681/89e2fc34-989a-491c-a475-a27f01a7dfb1)

**Comment by jasmine-97** [comment]
Perhaps it's an issue with my input coordinate system? Because, upon investigating the problem, I found that during the compute_3d_lanes_all_category process, all the lane lines are being categorized as invalid lane lines (if np.argmax(category) == 0: continue). Consequently, the output 3D points are empty. I wanted to ask, during the testing of the NuScenes dataset  with the camera parameters from the dataset,and chaning the ori_img_shape, have there been any modifications?"
